default:
  http_metas:
    content-type: text/html; charset=utf-8

  metas:
    title:        askeet! ask questions, find answers
    robots:       index, follow
    description:  symfony project
    keywords:     symfony, project
    language:     en

  stylesheets:    [main, layout]

  javascripts:    []

  has_layout:     on
  layout:         layout

  components:
    sidebar:      [sidebar, default]
