<?php
// auto-generated by sfPropelCrud
// date: 2013/12/16 23:41:33
?>
<?php //use_helper('Object') ?>

<?php if($sf_request->hasErrors()): ?>
  <p>投稿されたいずれかの項目が適切ではありません。下記のエラー内容を訂正し再投稿してください。</p>
  <ul>
  <?php foreach($sf_request->getErrors() as $error): ?>
    <li><?php echo $error ?></li>
  <?php endforeach ?>
  </ul>
  <br /><br />
<?php endif ?>
<?php echo form_tag('bbsdata/update') ?>

<?php// echo object_input_hidden_tag($bbsdata, 'getId') ?>

<table>
<tbody>
<tr>
  <th>タイトル:</th>
  <td>
<?php if($sf_params->get('oya_title')): ?>
 <?php echo input_tag('title','Re:'.$sf_params->get('oya_title'),array(
 'size'=>30,
 )) ?>
<?php else: ?>
<?php echo input_tag('title',$sf_params->get('title'), array (
  'size' => 30,
)) ?>
<?php endif; ?>
</td>
</tr>
<tr>
  <th>お名前:</th>
  <td><?php echo input_tag('author',$sf_params->get('author'), array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>メールアドレス:</th>
  <td><?php echo textarea_tag('mail',$sf_params->get('mail') , array (
  'size' => '30',
)) ?></td>
</tr>
<tr>
  <th>Url:</th>
  <td><?php echo textarea_tag('url', $sf_params->get('url'), array (
  'size' => '30',
)) ?></td>
</tr>
<tr>
  <th>内容:</th>
  <td>
<?php if($sf_params->get('oya_body')): ?>
 <?php echo textarea_tag('body',">".str_replace(
  "/n","/n>",$sf_params->get('oya_body')),array(
 'size' => '30x15'
)) ?>
<?php else: ?>
<?php echo textarea_tag('body',$sf_params->get('body'), array (
  'size' => '30x15',
)) ?>
<?php endif; ?>
</td>
</tr>
<tr>
  <th>削除用パスワード:</th>
  <td><?php echo input_tag('passwd', $sf_params->get('passwd'), array ('size' => 20,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo input_hidden_tag('parent_id',$sf_params->get('oya_id')) ?>
<?php echo submit_tag('この内容で投稿する') ?>
<?php// if ($bbsdata->getId()): ?>
  &nbsp;<?php// echo link_to('delete', 'bbsdata/delete?id='.$bbsdata->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php// echo link_to('cancel', 'bbsdata/show?id='.$bbsdata->getId()) ?>
<?php //else: ?>
  &nbsp;<?php echo link_to('cancel', 'bbsdata/list') ?>
<?php //endif; ?>
</form>
