<?php
// auto-generated by sfPropelCrud
// date: 2013/12/16 23:41:33
?>
<?php echo link_to('管理者ページヘ','/bbsdatakanri/login') ?>
<h1>My BBS</h1>
<div align="right">
<?php echo form_tag('bbsdata/search') ?>
<?php echo input_tag('kensaku_key','') ?>
<?php echo submit_tag('検索') ?>
</form>
</div>
<?php if($pager->haveToPaginate()): ?>
  <?php echo link_to('<<','bbsdata/list?page='.$pager->getFirstPage()) ?>
  <?php echo link_to('<','bbsdata/list?page='.$pager->getPreviousPage()) ?>
  <?php foreach($pager->getLinks() as $page): ?>
    <?php echo($page == $pager->getPage() ? $page:link_to($page,'bbsdata/list?page='.$page)) ?>
    <?php if($page != $pager->getCurrentMaxLink()): ?>
      -
    <?php endif ?>
  <?php endforeach ?>
  <?php echo link_to('>','bbsdata/list?page='.$pager->getNextPage()) ?>
  <?php echo link_to('>>','bbsdata/list?page='.$pager->getLastPage()) ?>
<?php endif ?>
<hr>
<?php foreach ($pager->getResults() as $bbsdata): ?>
<table>
<thead>
<tr>
  <th>Id</th>
  <th> タイトル</th>
  <th> お名前</th>
  <th> Date</th>
</tr>
</thead>
<tbody>
<tr>
    <td><?php echo $bbsdata->getId() ?></td>
    <td><big><?php echo $bbsdata->getTitle() ?></big></td>
    <?php if($bbsdata->getTitle() != "DELETED"): ?>
    <td><?php echo mail_to($bbsdata->getMail(),$bbsdata->getAuthor()) ?></td>
    <td><small>[<?php echo $bbsdata->getCreatedAt() ?>]</small></td>
    <td><?php echo link_to('Url',$bbsdata->getUrl()) ?></td>
    <?php endif ?>
</tr>
</tbody>
</table>
<br />
    <?php if($bbsdata->getTitle() != "DELETED"): ?>
<p><?php echo simple_format_text($bbsdata->getBody()) ?></p>
    <?php endif ?>
<br /><br />
<div align="right">
<?php echo form_tag('bbsdata/create') ?>
<?php echo input_hidden_tag('oya_id', $bbsdata->getId()) ?>
<?php echo input_hidden_tag('oya_title', $bbsdata->getTitle()) ?>
<?php echo input_hidden_tag('oya_body', $bbsdata->getBody()) ?>
<?php echo submit_tag('返信') ?>
</form>
<?php echo form_tag('bbsdata/sakujo') ?>
<?php echo input_password_tag('sakujo_key','') ?>
<?php echo input_hidden_tag('id',$bbsdata->getId()) ?>
<?php echo submit_tag('削除') ?>
</form>
</div>

<?php $th = 'threads'.$bbsdata->getId() ?>
  <div style='margin-left:20px'>
  <?php foreach($$th as $reply): ?>
  <table>
  <thead>
  <tr>
  <th>Id</th>
  <th> タイトル</th>
  <th> お名前</th>
  <th> Date</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td><?php echo $reply->getId() ?></td>
    <td><big><?php echo $reply->getTitle() ?></big></td>
    <?php if($reply->getTitle() != "DELETED"): ?>
    <td><?php echo mail_to($reply->getMail(),$reply->getAuthor()) ?></td>
    <td><small>[<?php echo $reply->getCreatedAt() ?>]</small></td>
    <td><?php echo link_to('Url',$reply->getUrl()) ?></td>
    <?php endif ?>
  </tr>
  </tbody>
  </table>
  <br />
    <?php if($reply->getTitle() != "DELETED"): ?>
  <p><?php echo simple_format_text($reply->getBody()) ?></p>
    <?php endif ?>
  <br /><br />
<div align="right">
<?php echo form_tag('bbsdata/sakujo') ?>
<?php echo input_password_tag('sakujo_key','') ?>
<?php echo input_hidden_tag('id',$reply->getId()) ?>
<?php echo submit_tag('削除') ?>
</form>
</div>
  <?php endforeach; ?>
  </div>

<hr>
<?php endforeach; ?>

<?php
 echo form_tag('bbsdata/create','create');
 echo input_hidden_tag('oya_id',0);
 echo submit_tag('投稿する');
?>
</form>
