<?php
// auto-generated by sfPropelAdmin
// date: 2014/02/18 00:03:39
?>
<?php echo form_tag('bbsdatakanri/save', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($bbsdata, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('bbsdata[title]', __($labels['bbsdata{title}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('bbsdata{title}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('bbsdata{title}')): ?>
    <?php echo form_error('bbsdata{title}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($bbsdata, 'getTitle', array (
  'size' => 50,
  'control_name' => 'bbsdata[title]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('bbsdata[author]', __($labels['bbsdata{author}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('bbsdata{author}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('bbsdata{author}')): ?>
    <?php echo form_error('bbsdata{author}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($bbsdata, 'getAuthor', array (
  'size' => 30,
  'control_name' => 'bbsdata[author]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('bbsdata[mail]', __($labels['bbsdata{mail}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('bbsdata{mail}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('bbsdata{mail}')): ?>
    <?php echo form_error('bbsdata{mail}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($bbsdata, 'getMail', array (
  'size' => '30x3',
  'control_name' => 'bbsdata[mail]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('bbsdata[url]', __($labels['bbsdata{url}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('bbsdata{url}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('bbsdata{url}')): ?>
    <?php echo form_error('bbsdata{url}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($bbsdata, 'getUrl', array (
  'size' => '30x3',
  'control_name' => 'bbsdata[url]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('bbsdata[body]', __($labels['bbsdata{body}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('bbsdata{body}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('bbsdata{body}')): ?>
    <?php echo form_error('bbsdata{body}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($bbsdata, 'getBody', array (
  'size' => '30x3',
  'control_name' => 'bbsdata[body]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('bbsdata[passwd]', __($labels['bbsdata{passwd}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('bbsdata{passwd}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('bbsdata{passwd}')): ?>
    <?php echo form_error('bbsdata{passwd}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($bbsdata, 'getPasswd', array (
  'size' => 20,
  'control_name' => 'bbsdata[passwd]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('bbsdata[parent_id]', __($labels['bbsdata{parent_id}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('bbsdata{parent_id}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('bbsdata{parent_id}')): ?>
    <?php echo form_error('bbsdata{parent_id}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($bbsdata, 'getParentId', array (
  'size' => 7,
  'control_name' => 'bbsdata[parent_id]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('bbsdata[created_at]', __($labels['bbsdata{created_at}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('bbsdata{created_at}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('bbsdata{created_at}')): ?>
    <?php echo form_error('bbsdata{created_at}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_date_tag($bbsdata, 'getCreatedAt', array (
  'rich' => true,
  'withtime' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'bbsdata[created_at]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('bbsdata' => $bbsdata)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($bbsdata->getId()): ?>
<?php echo button_to(__('delete'), 'bbsdatakanri/delete?id='.$bbsdata->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
