<?php
// auto-generated by sfPropelAdmin
// date: 2014/02/18 00:03:39
?>
    <td><?php echo link_to($bbsdata->getId() ? $bbsdata->getId() : __('-'), 'bbsdatakanri/edit?id='.$bbsdata->getId()) ?></td>
    <td><?php echo $bbsdata->getTitle() ?></td>
      <td><?php echo $bbsdata->getAuthor() ?></td>
      <td><?php echo $bbsdata->getMail() ?></td>
      <td><?php echo $bbsdata->getUrl() ?></td>
      <td><?php echo $bbsdata->getBody() ?></td>
      <td><?php echo $bbsdata->getPasswd() ?></td>
      <td><?php echo $bbsdata->getParentId() ?></td>
      <td><?php echo ($bbsdata->getCreatedAt() !== null && $bbsdata->getCreatedAt() !== '') ? format_date($bbsdata->getCreatedAt(), "f") : '' ?></td>
  