<?php
// auto-generated by sfPropelAdmin
// date: 2014/02/18 00:03:39
?>
  <th id="sf_admin_list_th_id">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/bbsdata/sort') == 'id'): ?>
      <?php echo link_to(__('Id'), 'bbsdatakanri/list?sort=id&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/bbsdata/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/bbsdata/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Id'), 'bbsdatakanri/list?sort=id&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_title">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/bbsdata/sort') == 'title'): ?>
      <?php echo link_to(__('Title'), 'bbsdatakanri/list?sort=title&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/bbsdata/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/bbsdata/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Title'), 'bbsdatakanri/list?sort=title&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_author">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/bbsdata/sort') == 'author'): ?>
      <?php echo link_to(__('Author'), 'bbsdatakanri/list?sort=author&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/bbsdata/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/bbsdata/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Author'), 'bbsdatakanri/list?sort=author&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_mail">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/bbsdata/sort') == 'mail'): ?>
      <?php echo link_to(__('Mail'), 'bbsdatakanri/list?sort=mail&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/bbsdata/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/bbsdata/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Mail'), 'bbsdatakanri/list?sort=mail&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_url">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/bbsdata/sort') == 'url'): ?>
      <?php echo link_to(__('Url'), 'bbsdatakanri/list?sort=url&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/bbsdata/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/bbsdata/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Url'), 'bbsdatakanri/list?sort=url&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_body">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/bbsdata/sort') == 'body'): ?>
      <?php echo link_to(__('Body'), 'bbsdatakanri/list?sort=body&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/bbsdata/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/bbsdata/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Body'), 'bbsdatakanri/list?sort=body&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_passwd">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/bbsdata/sort') == 'passwd'): ?>
      <?php echo link_to(__('Passwd'), 'bbsdatakanri/list?sort=passwd&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/bbsdata/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/bbsdata/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Passwd'), 'bbsdatakanri/list?sort=passwd&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_parent_id">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/bbsdata/sort') == 'parent_id'): ?>
      <?php echo link_to(__('Parent'), 'bbsdatakanri/list?sort=parent_id&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/bbsdata/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/bbsdata/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Parent'), 'bbsdatakanri/list?sort=parent_id&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_created_at">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/bbsdata/sort') == 'created_at'): ?>
      <?php echo link_to(__('Created at'), 'bbsdatakanri/list?sort=created_at&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/bbsdata/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/bbsdata/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Created at'), 'bbsdatakanri/list?sort=created_at&type=asc') ?>
      <?php endif; ?>
          </th>
