<?php
// auto-generated by sfPropelAdmin
// date: 2014/02/18 00:03:39
?>
<td colspan="9">
    <?php echo link_to($bbsdata->getId() ? $bbsdata->getId() : __('-'), 'bbsdatakanri/edit?id='.$bbsdata->getId()) ?>
     - 
    <?php echo $bbsdata->getTitle() ?>
     - 
    <?php echo $bbsdata->getAuthor() ?>
     - 
    <?php echo $bbsdata->getMail() ?>
     - 
    <?php echo $bbsdata->getUrl() ?>
     - 
    <?php echo $bbsdata->getBody() ?>
     - 
    <?php echo $bbsdata->getPasswd() ?>
     - 
    <?php echo $bbsdata->getParentId() ?>
     - 
    <?php echo ($bbsdata->getCreatedAt() !== null && $bbsdata->getCreatedAt() !== '') ? format_date($bbsdata->getCreatedAt(), "f") : '' ?>
     - 
</td>