<?php
// auto-generated by sfPropelAdmin
// date: 2014/02/18 00:03:39
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('create'), 'bbsdatakanri/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
</ul>
