<?php
// auto-generated by sfPropelAdmin
// date: 2014/02/18 00:03:39
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('edit bbsdatakanri', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('bbsdatakanri/edit_header', array('bbsdata' => $bbsdata)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('bbsdatakanri/edit_messages', array('bbsdata' => $bbsdata, 'labels' => $labels)) ?>
<?php include_partial('bbsdatakanri/edit_form', array('bbsdata' => $bbsdata, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('bbsdatakanri/edit_footer', array('bbsdata' => $bbsdata)) ?>
</div>

</div>
