<?php
// auto-generated by sfPropelCrud
// date: 2014/01/01 18:03:03
?>
<h1>popular question</h1>

<?php echo include_partial('list',array('question_pager'=>$question_pager,'rule'=>'question/list')) ?>
