<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/01/22 16:50:20
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
