<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/01/15 15:47:19

$database = new sfPropelDatabase();
$database->initialize(array (
  'dsn' => 'mysql://devuser:Ganba4649@localhost/mysite_murai',
  'encode' => 'utf8',
), 'propel');
$this->databases['propel'] = $database;
