<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/02/18 00:03:39
$this->security = array (
  'login' => 
  array (
    'is_secure' => false,
  ),
  'logout' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'admin',
  ),
);
