<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/01/09 09:57:29
$this->security = array (
  'add' => 
  array (
    'is_secure' => true,
    'credentials' => 'subscriber',
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
