<?php
// auto-generated by sfPropelCrud
// date: 2014/01/01 18:03:03
?>
<?php

/**
 * question actions.
 *
 * @package    mysite
 * @subpackage question
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class questionActions extends sfActions
{

  public function executeList()
  {
    $this->question_pager = QuestionPeer::getHomepagePager($this->getRequestParameter('page',1));
   }

  public function executeShow()
  {
    $this->question = QuestionPeer::getQuestionFromTitle($this->getRequestParameter('stripped_title'));

    $this->forward404Unless($this->question);
  }

  public function executeRecent()
  {
    $this->question_pager = QuestionPeer::getRecentPager($this->getRequestParameter('page',1));
  }

  public function executeAdd()
  { 
    if($this->getRequest()->getMethod() == sfRequest::POST)
    {
      $user = $this->getUser()->getSubscriber();

      $question = new Question();
      $question->setTitle($this->getRequestParameter('title'));
      $question->setBody($this->getRequestParameter('body'));
      $question->setUser($user);
      $question->save();

      $user->isInterestedIn($question);

      return $this->redirect('@question?stripped_title='.$question->getStrippedTitle());
      }
  }

  public function handleErrorAdd()
  {
    return sfView::SUCCESS;
  }
}
